export enum CashMovementTypeEnum {
  INCOME = 'INCOME',
  EXPENSE = 'EXPENSE',
  ADJUSTMENT_INCOME = 'ADJUSTMENT_INCOME',
  ADJUSTMENT_EXPENSE = 'ADJUSTMENT_EXPENSE',
  SALE = 'SALE',
  REFUND = 'REFUND',
}
