export enum MovementTypeEnum {
  IN = 'IN',
  OUT = 'OUT',
  ADJUSTMENT_IN = 'ADJUSTMENT_IN',
  ADJUSTMENT_OUT = 'ADJUSTMENT_OUT',
  TRANSFER_IN = 'TRANSFER_IN',
  TRANSFER_OUT = 'TRANSFER_OUT',
}

export enum MovementReasonEnum {
  PURCHASE = 'PURCHASE',
  RECIPE_USAGE = 'RECIPE_USAGE',
  MANUAL_ADJUSTMENT = 'MANUAL_ADJUSTMENT',
  EXPIRY = 'EXPIRY',
  DAMAGE = 'DAMAGE',
  TRANSFER = 'TRANSFER',
}

export enum ReferenceTypeEnum {
  ORDER = 'ORDER',
  PURCHASE = 'PURCHASE',
  MANUAL = 'MANUAL',
  TRANSFER = 'TRANSFER',
  RECIPE = 'RECIPE',
}
