export enum TableStatusEnum {
  AVAILABLE = 'AVAILABLE',
  OCCUPIED = 'OCCUPIED',
  RESERVED = 'RESERVED',
  READY_TO_PAY = 'READY_TO_PAY',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
  NEED_CLEANING = 'NEED_CLEANING',
}
